package infraguard.packs.aliyun.compliance

import rego.v1

pack_meta := {
	"id": "compliance",
	"name": {
		"en": "Cloud Compliance Pack",
		"zh": "云基础设施合规包",
		"ja": "クラウドコンプライアンスパック",
		"de": "Cloud-Compliance-Paket",
		"es": "Paquete de Cumplimiento Cloud",
		"fr": "Pack de Conformite Cloud",
		"pt": "Pacote de Conformidade Cloud"
	},
	"description": {
		"en": "Directory roll-up of Alibaba Cloud compliance packs, covering security baselines, regulatory frameworks, governance, encryption, logging, access controls, and resilience checks.",
		"zh": "阿里云合规目录级总包，汇总安全基线、监管框架、治理、加密、日志、访问控制和韧性相关检查。",
		"ja": "Alibaba Cloud のコンプライアンス pack をディレクトリ単位で集約し、セキュリティベースライン、規制フレームワーク、ガバナンス、暗号化、ログ、アクセス制御、レジリエンスを確認します。",
		"de": "Directory-Roll-up der Alibaba-Cloud-Compliance-Packs fuer Sicherheitsbaselines, regulatorische Frameworks, Governance, Verschluesselung, Logging, Zugriffskontrollen und Resilienz.",
		"es": "Roll-up de directorio de packs de cumplimiento de Alibaba Cloud para lineas base de seguridad, marcos regulatorios, gobernanza, cifrado, logs, controles de acceso y resiliencia.",
		"fr": "Roll-up de repertoire des packs de conformite Alibaba Cloud pour les bases de securite, cadres reglementaires, gouvernance, chiffrement, journaux, controles d'acces et resilience.",
		"pt": "Roll-up de diretorio dos packs de conformidade do Alibaba Cloud para baselines de seguranca, frameworks regulatorios, governanca, criptografia, logs, controles de acesso e resiliencia."
	},
	"rules": [
		"ack-cluster-encryption-enabled",
		"ack-cluster-node-multi-zone",
		"ack-cluster-public-endpoint-check",
		"ack-cluster-rrsa-enabled",
		"ack-cluster-supported-version",
		"ack-cluster-upgrade-latest-version",
		"actiontrail-enabled",
		"actiontrail-trail-intact-enabled",
		"alb-all-listener-health-check-enabled",
		"alb-instance-multi-zone",
		"alb-server-group-multi-zone",
		"api-gateway-api-internet-request-https",
		"api-gateway-group-enabled-ssl",
		"cr-repository-immutablity-enable",
		"ecs-available-disk-encrypted",
		"ecs-disk-auto-snapshot-policy",
		"ecs-disk-encrypted",
		"ecs-in-use-disk-encrypted",
		"ecs-instance-attached-security-group",
		"ecs-instance-deletion-protection-enabled",
		"ecs-instance-enabled-security-protection",
		"ecs-instance-expired-check",
		"ecs-instance-not-bind-key-pair",
		"ecs-instance-ram-role-attached",
		"ecs-instances-in-vpc",
		"ecs-running-instance-no-public-ip",
		"ecs-security-group-risky-ports-check-with-protocol",
		"ecs-security-group-white-list-port-check",
		"ecs-snapshot-policy-timepoints-check",
		"ecs-snapshot-retention-days",
		"eip-attached",
		"eip-bandwidth-limit",
		"elasticsearch-instance-enabled-data-node-encryption",
		"elasticsearch-instance-multi-zone",
		"elasticsearch-public-and-any-ip-access-check",
		"ess-scaling-configuration-enabled-internet-check",
		"ess-scaling-group-attach-multi-switch",
		"fc-function-custom-domain-and-tls-enable",
		"fc-service-bind-role",
		"fc-service-internet-access-disable",
		"fc-service-vpc-binding",
		"firewall-asset-open-protect",
		"hbase-cluster-deletion-protection",
		"hbase-cluster-expired-check",
		"hbase-cluster-in-vpc",
		"hbase-cluster-type-check",
		"kms-key-delete-protection-enabled",
		"kms-key-rotation-enabled",
		"kms-secret-rotation-enabled",
		"maxcompute-project-encryption-enabled",
		"maxcompute-project-ip-whitelist-enabled",
		"mongodb-cluster-expired-check",
		"mongodb-instance-log-audit",
		"mongodb-instance-multi-zone",
		"mongodb-instance-release-protection",
		"mongodb-public-access-check",
		"mse-cluster-config-auth-enabled",
		"nas-filesystem-encrypt-type-check",
		"nas-filesystem-mount-target-access-group-check",
		"oss-bucket-anonymous-prohibited",
		"oss-bucket-authorize-specified-ip",
		"oss-bucket-logging-enabled",
		"oss-bucket-only-https-enabled",
		"oss-bucket-policy-no-any-anonymous",
		"oss-bucket-policy-outside-organization-check",
		"oss-bucket-public-read-prohibited",
		"oss-bucket-public-write-prohibited",
		"oss-bucket-referer-limit",
		"oss-bucket-server-side-encryption-enabled",
		"oss-bucket-versioning-enabled",
		"oss-default-encryption-kms",
		"oss-encryption-byok-check",
		"oss-zrs-enabled",
		"pai-eas-instances-multi-zone",
		"polardb-cluster-delete-protection-enabled",
		"polardb-cluster-enabled-ssl",
		"polardb-cluster-enabled-tde",
		"polardb-cluster-expired-check",
		"polardb-cluster-maintain-time-check",
		"polardb-cluster-multi-zone",
		"polardb-public-and-any-ip-access-check",
		"privatelink-servier-endpoint-multi-zone",
		"ram-group-has-member-check",
		"ram-password-policy-check",
		"ram-policy-no-statements-with-admin-access-check",
		"ram-user-activated-ak-quantity-check",
		"ram-user-ak-create-date-expired-check",
		"ram-user-ak-used-expired-check",
		"ram-user-group-membership-check",
		"ram-user-last-login-expired-check",
		"ram-user-login-check",
		"ram-user-mfa-check",
		"ram-user-no-policy-check",
		"rds-instacne-delete-protection-enabled",
		"rds-instance-enabled-auditing",
		"rds-instance-enabled-disk-encryption",
		"rds-instance-enabled-log-backup",
		"rds-instance-enabled-ssl",
		"rds-instance-expired-check",
		"rds-instance-has-guard-instance",
		"rds-instance-maintain-time-check",
		"rds-instances-in-vpc",
		"rds-multi-az-support",
		"rds-public-access-check",
		"rds-public-connection-and-any-ip-access-check",
		"rds-white-list-internet-ip-access-check",
		"redis-instance-backup-log-enabled",
		"redis-instance-enabled-byok-tde",
		"redis-instance-enabled-ssl",
		"redis-instance-expired-check",
		"redis-instance-multi-zone",
		"redis-instance-open-auth-mode",
		"redis-instance-release-protection",
		"redis-public-and-any-ip-access-check",
		"root-ak-check",
		"root-has-specified-role",
		"root-mfa-check",
		"security-center-version-check",
		"sg-public-access-check",
		"slb-acl-public-access-check",
		"slb-all-listener-servers-multi-zone",
		"slb-all-listenter-tls-policy-check",
		"slb-delete-protection-enabled",
		"slb-instance-log-enabled",
		"slb-instance-multi-zone",
		"slb-listener-https-enabled",
		"slb-listener-risk-ports-check",
		"slb-loadbalancer-bandwidth-limit",
		"slb-vserver-group-multi-zone",
		"sls-logstore-enabled-encrypt",
		"sls-project-multi-zone",
		"use-waf-instance-for-security-protection",
		"vpc-flow-logs-enabled",
		"vpc-network-acl-risky-ports-check",
		"vswitch-available-ip-count",
		"waf-instance-logging-enabled"
	]
}
