package infraguard.packs.aliyun.security

import rego.v1

pack_meta := {
	"id": "security",
	"name": {
		"en": "Security Scenario Pack",
		"zh": "安全性场景合规包",
		"ja": "セキュリティシナリオパック",
		"de": "Sicherheitsszenario-Paket",
		"es": "Paquete de escenarios de seguridad",
		"fr": "Pack de scenarios de securite",
		"pt": "Pacote de cenarios de seguranca"
	},
	"description": {
		"en": "Directory roll-up of Alibaba Cloud security packs, covering identity, network exposure, data protection, audit logging, supply chain, key management, platform security, and security group controls.",
		"zh": "阿里云安全性目录级总包，汇总身份、网络暴露、数据保护、审计日志、供应链、密钥管理、平台安全和安全组控制相关检查。",
		"ja": "Alibaba Cloud のセキュリティ pack をディレクトリ単位で集約し、ID、ネットワーク公開、データ保護、監査ログ、サプライチェーン、鍵管理、プラットフォームセキュリティ、セキュリティグループ制御を確認します。",
		"de": "Directory-Roll-up der Alibaba-Cloud-Security-Packs fuer Identitaet, Netzwerkexposition, Datenschutz, Audit-Logging, Lieferkette, Schluesselverwaltung, Plattform-Sicherheit und Security-Group-Kontrollen.",
		"es": "Roll-up de directorio de packs de seguridad de Alibaba Cloud para identidad, exposicion de red, proteccion de datos, auditoria, cadena de suministro, gestion de claves, seguridad de plataforma y grupos de seguridad.",
		"fr": "Roll-up de repertoire des packs de securite Alibaba Cloud pour identite, exposition reseau, protection des donnees, audit, chaine d'approvisionnement, gestion des cles, securite de plateforme et groupes de securite.",
		"pt": "Roll-up de diretorio dos packs de seguranca do Alibaba Cloud para identidade, exposicao de rede, protecao de dados, auditoria, cadeia de suprimentos, gerenciamento de chaves, seguranca de plataforma e grupos de seguranca."
	},
	"rules": [
		"ack-cluster-public-endpoint-check",
		"ack-cluster-rrsa-enabled",
		"actiontrail-trail-intact-enabled",
		"api-gateway-api-auth-required",
		"api-gateway-api-internet-request-https",
		"api-gateway-group-enabled-ssl",
		"cr-repository-image-scanning-enabled",
		"cr-repository-type-private",
		"ecs-disk-auto-snapshot-policy",
		"ecs-disk-idle-check",
		"ecs-in-use-disk-encrypted",
		"ecs-instance-attached-security-group",
		"ecs-instance-enabled-security-protection",
		"ecs-instance-login-use-keypair",
		"ecs-instance-ram-role-attached",
		"ecs-instances-in-vpc",
		"ecs-running-instance-no-public-ip",
		"ecs-security-group-egress-not-all-access",
		"ecs-security-group-not-internet-cidr-access",
		"ecs-security-group-not-open-all-port",
		"ecs-security-group-not-open-all-protocol",
		"ecs-security-group-risky-ports-check-with-protocol",
		"ecs-security-group-white-list-port-check",
		"elasticsearch-instance-enabled-data-node-encryption",
		"elasticsearch-public-and-any-ip-access-check",
		"emr-cluster-master-public-access-check",
		"ess-scaling-configuration-enabled-internet-check",
		"fc-service-bind-role",
		"fc-service-internet-access-disable",
		"fc-service-vpc-binding",
		"kms-key-rotation-enabled",
		"kms-secret-rotation-enabled",
		"mongodb-public-and-any-ip-access-check",
		"mse-cluster-config-auth-enabled",
		"nas-filesystem-encrypt-type-check",
		"oss-bucket-anonymous-prohibited",
		"oss-bucket-logging-enabled",
		"oss-bucket-only-https-enabled",
		"oss-bucket-policy-no-any-anonymous",
		"oss-bucket-public-read-prohibited",
		"oss-bucket-public-write-prohibited",
		"oss-bucket-server-side-encryption-enabled",
		"oss-bucket-versioning-enabled",
		"oss-encryption-byok-check",
		"polardb-cluster-enabled-ssl",
		"polardb-public-and-any-ip-access-check",
		"ram-group-has-member-check",
		"ram-password-policy-check",
		"ram-policy-no-statements-with-admin-access-check",
		"ram-user-activated-ak-quantity-check",
		"ram-user-ak-create-date-expired-check",
		"ram-user-ak-used-expired-check",
		"ram-user-group-membership-check",
		"ram-user-last-login-expired-check",
		"ram-user-login-check",
		"ram-user-mfa-check",
		"ram-user-no-product-admin-access",
		"rds-instance-enabled-log-backup",
		"rds-instance-enabled-ssl",
		"rds-instance-enabled-tde-disk-encryption",
		"rds-public-access-check",
		"rds-public-connection-and-any-ip-access-check",
		"redis-instance-backup-log-enabled",
		"redis-instance-enabled-ssl",
		"redis-instance-no-public-ip",
		"redis-public-and-any-ip-access-check",
		"root-ak-check",
		"root-mfa-check",
		"security-center-version-check",
		"security-ecs-disk-encrypted",
		"security-ecs-instance-security-group-required",
		"security-ecs-instance-vpc-required",
		"security-rds-instance-vpc-required",
		"security-redis-instance-vpc-required",
		"sg-public-access-check",
		"slb-acl-public-access-check",
		"slb-instance-log-enabled",
		"slb-listener-https-enabled",
		"slb-listener-risk-ports-check",
		"vpc-flow-logs-enabled",
		"vpc-network-acl-risky-ports-check",
		"waf-instance-logging-enabled"
	]
}
