package infraguard.packs.aliyun.iso_27001_compliance

import rego.v1

pack_meta := {
	"id": "iso-27001-compliance",
	"name": {
		"en": "ISO-27001 Security Management Standard Compliance",
		"zh": "ISO-27001 安全管理标准合规包",
	},
	"description": {
		"en": "Compliance pack for ISO-27001 Information Security Management System standard. This pack helps organizations verify their cloud resources meet ISO-27001 security requirements.",
		"zh": "ISO-27001 信息安全管理体系标准合规包。本合规包帮助组织验证其云资源是否符合 ISO-27001 安全要求。",
	},
	"rules": [
		"ack-cluster-public-endpoint-check",
		# "ack-cluster-node-monitorenabled",
		"ack-cluster-node-multi-zone",
		# "ack-cluster-deletion-protection-enabled",
		# "adb-public-access-check",  # Commented: ROS ADB::DBCluster does not support PublicEndpoint property
		# "adb-cluster-log-backup-enabled",
		"alb-instance-multi-zone",
		"alb-all-listener-health-check-enabled",
		# "api-gateway-group-log-enabled",
		# "cdn-domain-tls13-enabled",
		# "dts-instance-sync-job-ssl-enabled",
		"ecs-snapshot-policy-timepoints-check",
		# "resource-group-default-used-check",
		"ecs-in-use-disk-encrypted",
		"ecs-available-disk-encrypted",
		"ecs-disk-auto-snapshot-policy",
		# "resources-inherit-resourcegroup-from-ecs-instance",
		"ecs-instance-enabled-security-protection",
		# "ecs-instance-monitor-enabled",  # Commented: ROS ECS::Instance does not support CloudMonitorFlags property
		# "ecs-running-instances-in-vpc",
		# "ecs-instance-meta-data-mode-check",
		"ecs-running-instance-no-public-ip",
		# "ecs-instance-updated-security-vul",  # Commented: ROS ECS::Instance does not support Vulnerabilities property
		"ecs-security-group-risky-ports-check-with-protocol",
		# "ess-group-health-check",
		"ess-scaling-group-attach-multi-switch",
		# "elasticsearch-instance-enabled-public-check",
		"elasticsearch-instance-enabled-data-node-encryption",
		"fc-function-custom-domain-and-tls-enable",
		# "fc-function-settings-check",
		"fc-service-vpc-binding",
		"fc-service-internet-access-disable",
		"kms-key-rotation-enabled",
		# "kms-key-state-not-pending-deletion",  # Commented: ROS KMS::Key does not support KeyState property (runtime state only)
		# "kms-secret-last-rotation-date-check",
		"kms-secret-rotation-enabled",
		"maxcompute-project-encryption-enabled",
		# "nas-filesystem-enable-backup-plan",
		"nas-filesystem-encrypt-type-check",
		"oss-bucket-public-write-prohibited",
		"oss-bucket-public-read-prohibited",
		"oss-zrs-enabled",
		"oss-default-encryption-kms",
		"oss-bucket-versioning-enabled",
		"oss-bucket-logging-enabled",
		"oss-bucket-only-https-enabled",
		# "ots-instance-all-table-encrypted",  # ROS template does not support SSESpecification property
		# "polardb-cluster-address-no-public",
		# "polardb-public-access-check",
		"polardb-cluster-enabled-tde",
		"polardb-cluster-maintain-time-check",
		# "polardb-cluster-level-one-backup-retention",
		# "polardb-cluster-enabled-auditing",  # ROS does not support SQLCollectorStatus property
		# "polardb-cluster-log-backup-retention",  # ROS does not support LogBackupRetentionPeriod property
		"polardb-cluster-enabled-ssl",
		"polardb-cluster-delete-protection-enabled",
		"polardb-cluster-multi-zone",
		# "ram-group-in-use-check",
		"ram-group-has-member-check",
		"ram-policy-no-statements-with-admin-access-check",
		# "ram-policy-in-use-check",
		"ram-user-mfa-check",
		"ram-user-ak-create-date-expired-check",
		"ram-user-login-check",
		"ram-user-no-policy-check",
		"ram-user-no-policy-check",
		"rds-public-access-check",
		"rds-instance-enabled-log-backup",
		"rds-multi-az-support",
		# "rds-instance-enabled-tde",
		"rds-instance-maintain-time-check",
		"redis-instance-backup-log-enabled",
		"slb-listener-https-enabled",
		"slb-delete-protection-enabled",
		"slb-instance-log-enabled",
		# "slb-aliyun-certificate-required",
		# "ssl-certificate-expired-check",
		"vpc-flow-logs-enabled",
		"vswitch-available-ip-count",
		# "vpn-ipsec-connection-status-check",
	],
}
