package infraguard.packs.aliyun.mlps_level_3_pre_check_compliance_pack

import rego.v1

pack_meta := {
	"id": "mlps-level-3-pre-check-compliance-pack",
	"name": {
		"en": "MLPS Level 3 Pre-check Compliance Pack",
		"zh": "等保三级预检合规包",
	},
	"description": {
		"en": "Compliance pack for MLPS level 3 pre-check requirements on Aliyun resources.",
		"zh": "基于等保三级的部分要求，对阿里云上资源的合规性做检测。",
	},
	"rules": [
		"use-waf-instance-for-security-protection",
		# "use-ddos-instance-for-security-protection",
		# "use-cloud-fire-wall-for-security-protection",
		# "security-center-defense-config-check",
		"actiontrail-trail-intact-enabled",
		# "ram-password-require-char-check",  # Commented: ROS does not support ALIYUN::RAM::PasswordPolicy resource type
		# "ram-password-max-age-check",  # Commented: ROS does not support ALIYUN::RAM::PasswordPolicy resource type
		# "ram-password-max-login-attemps-check",  # Commented: ROS does not support ALIYUN::RAM::PasswordPolicy resource type
		"root-mfa-check",
		# "security-center-notice-config-check",
		"security-center-version-check",
		"ack-cluster-public-endpoint-check",
		"ack-cluster-node-multi-zone",
		"ack-cluster-encryption-enabled",
		# "adb-cluster-audit-log-enabled",  # Commented: ROS ADB::DBCluster does not support AuditLog property
		"alb-instance-multi-zone",
		# "alb-all-listener-enabled-acl",  # Commented: ROS ALB::Listener does not support AclConfig property
		# "api-gateway-group-https-policy-check",
		# "cdn-domain-tls13-enabled",
		# "cen-cross-region-bandwidth-check",
		# "cr-instance-any-ip-access-check",
		"firewall-asset-open-protect",
		"ecs-in-use-disk-encrypted",
		"ecs-disk-auto-snapshot-policy",
		"ecs-instance-enabled-security-protection",
		"ecs-instances-in-vpc",
		"ecs-running-instance-no-public-ip",
		# "ecs-instance-updated-security-vul",  # Commented: ROS ECS::Instance does not support Vulnerabilities property
		"sg-public-access-check",
		"ecs-security-group-risky-ports-check-with-protocol",
		"eip-bandwidth-limit",
		"elasticsearch-public-and-any-ip-access-check",
		"elasticsearch-instance-multi-zone",
		# "elasticsearch-instance-snapshot-enabled",  # Commented: ROS does not support AutoSnapshot property for ALIYUN::ElasticSearch::Instance
		"mongodb-instance-multi-zone",
		# "mongodb-instance-backup-log-enabled",  # Commented: ROS does not support ALIYUN::MongoDB::DBInstance resource type
		"nas-filesystem-mount-target-access-group-check",
		# "nas-filesystem-enable-backup-plan",
		# "natgateway-snat-eip-bandwidth-check",
		# "nat-risk-ports-check",
		"oss-bucket-policy-no-any-anonymous",
		"oss-bucket-public-read-prohibited",
		"oss-zrs-enabled",
		"oss-bucket-policy-outside-organization-check",
		"oss-default-encryption-kms",
		"oss-bucket-versioning-enabled",
		"oss-bucket-only-https-enabled",
		"oss-bucket-authorize-specified-ip",
		# "oss-bucket-referer-enabled",
		"polardb-public-and-any-ip-access-check",
		"polardb-cluster-enabled-ssl",
		"polardb-cluster-enabled-tde",
		"polardb-cluster-multi-zone",
		# "polardb-cluster-level-two-backup-retention",
		"ram-group-has-member-check",
		"ram-policy-no-statements-with-admin-access-check",
		# "ram-policy-in-use-check",
		"ram-user-mfa-check",
		"ram-user-last-login-expired-check",
		"ram-user-no-policy-check",
		"ram-user-ak-used-expired-check",
		"ram-user-login-check",
		"rds-public-connection-and-any-ip-access-check",
		"rds-instance-enabled-log-backup",
		"rds-multi-az-support",
		"rds-instances-in-vpc",
		# "rds-instance-tls-version-check",
		"rds-instance-enabled-auditing",
		"rds-instance-enabled-disk-encryption",
		"rds-instance-has-guard-instance",
		"redis-instance-open-auth-mode",
		"redis-public-and-any-ip-access-check",
		"redis-instance-multi-zone",
		# "redis-instance-in-vpc",
		# "redis-instance-enabled-tde",
		"slb-acl-public-access-check",
		"slb-all-listenter-tls-policy-check",
		"slb-listener-risk-ports-check",
		"slb-all-listener-servers-multi-zone",
		# "slb-no-public-ip",
		# "slb-all-listener-enabled-acl",
		"slb-loadbalancer-bandwidth-limit",
		"sls-logstore-enabled-encrypt",
		"vpc-network-acl-risky-ports-check",
		"vpc-flow-logs-enabled",
		# "waf3-instance-enabled-specified-defense-rules",
	],
}
