# Resource Stability Best Practice Pack
# Detect resource stability from six dimensions: high availability, capacity protection,
# change management, monitoring, backup, and fault isolation.
package infraguard.packs.aliyun.resource_stability_best_practice

import rego.v1

# Pack metadata with i18n support
pack_meta := {
	"id": "resource-stability-best-practice",
	"name": {
		"en": "Resource Stability Best Practice",
		"zh": "资源稳定性最佳实践",
	},
	"description": {
		"en": "Detect resource stability from six dimensions: high availability architecture, capacity protection, change management, monitoring management, backup management, and fault isolation, which helps to identify risks in advance and improve stability and O&M efficiency.",
		"zh": "从高可用基础架构、容量保护、变更管理、监控管理、备份管理、故障隔离六大维度对云上资源的稳定性做检测，有助于提前发现隐患，提升稳定性和运维效率。",
	},
	"rules": [
		# "region-vswitch-no-crossed-cidr",
		"ack-cluster-upgrade-latest-version",
		# "ack-cluster-deletion-protection-enabled",
		# "ack-cluster-spec-check",
		# "adb-cluster-expired-check",
		# "adb-cluster-maintain-time-check",  # Commented: ROS ADB::DBCluster does not support MaintainTime property
		# "adb-cluster-log-backup-enabled",
		"alb-all-listener-health-check-enabled",
		"alb-all-listenter-has-server",
		"alb-delete-protection-enabled",
		# "kafka-instance-public-access-check",
		"bastionhost-instance-expired-check",
		# "cbwp-bandwidth-package-expired-check",
		# "cdn-domain-enabled-cache",
		# "cdn-domain-oss-source-check",
		# "cen-bandwidth-package-expired-check",
		# "cen-all-vbr-health-check-enabled",
		# "cen-cross-region-bandwidth-check",
		# "polardb-x1-instance-expired-check",
		# "polardb-x2-instance-expired-check",
		# "ddoscoo-instance-expired-check",
		# "eci-container-group-volumn-mounts",
		"ecs-snapshot-policy-timepoints-check",
		"ecs-disk-auto-snapshot-policy",
		"ecs-instance-expired-check",
		"ecs-instance-deletion-protection-enabled",
		# "ecs-instance-status-no-stopped",  # Commented: ROS ECS::Instance does not support Status property
		# "ecs-instance-type-family-not-deprecated",
		# "ecs-instance-os-name-check",
		"ecs-security-group-risky-ports-check-with-protocol",
		# "eip-address-expired-check",
		"eip-delete-protection-enabled",
		"elasticsearch-public-and-any-ip-access-check",
		# "elasticsearch-instance-version-not-deprecated",
		# "elasticsearch-instance-enabled-kibana-public-check",
		"elasticsearch-instance-multi-zone",
		# "elasticsearch-instance-node-not-use-specified-spec",
		# "elasticsearch-instance-snapshot-enabled",  # Commented: ROS does not support AutoSnapshot property for ALIYUN::ElasticSearch::Instance
		"mongodb-cluster-expired-check",
		"mongodb-public-access-check",
		# "mongodb-instance-multi-node",
		"mongodb-instance-release-protection",
		"mongodb-instance-multi-zone",
		# "mongodb-instance-backup-log-enabled",  # Commented: ROS does not support ALIYUN::MongoDB::DBInstance resource type
		# "mongodb-instance-class-not-shared",
		# "natgateway-eip-used-check",
		# "natgateway-snat-eip-bandwidth-check",
		"oss-bucket-public-write-prohibited",
		"oss-zrs-enabled",
		"oss-bucket-versioning-enabled",
		# "ons-instance-type-check",
		"polardb-cluster-expired-check",
		# "polardb-public-access-check",
		"polardb-cluster-maintain-time-check",
		# "polardb-dbversion-status-check",
		"polardb-cluster-delete-protection-enabled",
		"polardb-cluster-multi-zone",
		# "polardb-cluster-category-normal",
		# "polardb-cluster-level-two-backup-retention",
		"rds-instance-enabled-log-backup",
		"rds-multi-az-support",
		"rds-public-access-check",
		# "rds-instance-enabled-security-ip-list",
		"rds-instance-expired-check",
		# "rds-instance-class-type-check",
		# "rds-instance-sql-collector-retention",  # Commented: ROS RDS::DBInstance does not support SQLCollectorRetention property
		"rds-instance-maintain-time-check",
		"rds-instacne-delete-protection-enabled",
		# "rds-instance-category-check",
		"redis-instance-expired-check",
		# "redis-public-access-check",
		# "redis-instance-disable-risk-commands",
		# "redis-architecturetype-cluster-check",
		"redis-instance-multi-zone",
		"redis-instance-backup-time-check",
		# "redis-instance-upgrade-latest-version",
		"redis-instance-release-protection",
		# "redis-instance-edition-type-check",
		"redis-instance-backup-log-enabled",
		"slb-all-listener-health-check-enabled",
		# "slb-instance-expired-check",
		"slb-delete-protection-enabled",
		"slb-all-listener-servers-multi-zone",
		"slb-instance-multi-zone",
		# "slb-instance-spec-check",
	],
}
